//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSR_Helper.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_tab_dish = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_dish_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_dish_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int whitey = 2130837509;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int button1 = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int editText1 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int editText2 = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int gridView1 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int horizontalScrollView2 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dish = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Setting = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int helloButtonText = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int helloLabelText = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int lunchtable = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int settings = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int timetable = 2130968579;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
