#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HSR_Helper.Android.Resource", IsApplication=true)]

namespace HSR_Helper.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int day_title = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int entry = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int entry_text = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int title_text = 2131099649;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_tab_dish = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_dish_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_dish_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menu = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int navigation_next_item = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int navigation_previous_item = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int settings = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int timetable = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int whitey = 2130837514;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int day_text = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int description = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int dish_list = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int dish_title = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int lession_list = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout2 = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int nextDay = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int password = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int previousDay = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int price = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int relativeLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int saldo = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int saveButton = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int textView1 = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int text_from = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int text_lecturers = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int text_lesson = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int text_room = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int text_to = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int timetable_list = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int userName = 2131165192;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DishDay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DishItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Setting = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TimeSlotItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TimetableDay = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TimetableItem = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int enterUser = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int lunchtable = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int pwd = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int settings = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int timetable = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int userName = 2130968580;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
